<a href="https://colab.research.google.com/github/AngelTroncoso/Alergias/blob/main/01_1_analisis_con_rfam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import json
import requests

r = requests.get('https://rfam.org/family/RF00360?content-type=application/json')
print(r.json()['rfam']['acc'])

RF00360

In [3]:
import json
import requests

# Realizamos la petición GET para obtener los datos nuevamente
r = requests.get('https://rfam.org/family/RF00360?content-type=application/json')

# Obtenemos el contenido JSON de la respuesta
data = r.json()

# Definimos el nombre del archivo donde guardaremos los datos
file_name = 'rfam_RF00360.json'

# Guardamos los datos en un archivo JSON local
with open(file_name, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Datos guardados exitosamente en '{file_name}'")

Datos guardados exitosamente en 'rfam_RF00360.json'

In [4]:
import pandas as pd
import json

# El nombre del archivo JSON que guardamos anteriormente
file_name = 'rfam_RF00360.json'

# Abrimos y cargamos el archivo JSON
with open(file_name, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Convertimos el diccionario a un DataFrame de pandas
# Dado que la estructura del JSON puede ser compleja, empezaremos con la clave 'rfam'
df = pd.json_normalize(data['rfam'])

print(f"El archivo '{file_name}' ha sido cargado en un DataFrame de pandas.")

# Mostramos las primeras filas del DataFrame para su inspección
display(df.head())

El archivo 'rfam_RF00360.json' ha sido cargado en un DataFrame de pandas.

,id,comment,acc,description,cm.build_command,cm.calibrate_command,cm.search_command,cm.cutoffs.noise,cm.cutoffs.trusted,cm.cutoffs.gathering,...,clan.id,release.number,release.date,curation.num_full,curation.num_seed,curation.seed_source,curation.type,curation.author,curation.structure_source,curation.num_species
0,snoZ107_R87,Z107 and R87 are members of the C/D class of s...,RF00360,Small nucleolar RNA Z107/R87,cmbuild -F CM SEED,cmcalibrate --mpi CM,cmsearch --cpu 4 --verbose --nohmmonly -T 19.0...,49.7,50.0,50.0,...,None,15.1,2026-01-16,783,9,Moxon SJ,Gene; snRNA; snoRNA; CD-box;,Moxon SJ,"Predicted; RNAfold; Moxon SJ, Daub J, Gardner PP",221

In [5]:
print('--- Información general del DataFrame (Tipos de datos y valores no nulos) ---')
df.info()

print('\n--- Conteo de valores nulos por columna ---')
print(df.isnull().sum())

--- Información general del DataFrame (Tipos de datos y valores no nulos) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         1 non-null      object
 1   comment                    1 non-null      object
 2   acc                        1 non-null      object
 3   description                1 non-null      object
 4   cm.build_command           1 non-null      object
 5   cm.calibrate_command       1 non-null      object
 6   cm.search_command          1 non-null      object
 7   cm.cutoffs.noise           1 non-null      float64
 8   cm.cutoffs.trusted         1 non-null      float64
 9   cm.cutoffs.gathering       1 non-null      float64
 10  clan.acc                   0 non-null      object
 11  clan.id                    0 non-null      object
 12  release.number             1 non-null      object
 13  release.date               1 non-null      object
 14  curation.num_full          1 non-null      int64
 15  curation.num_seed          1 non-null      int64
 16  curation.seed_source       1 non-null      object
 17  curation.type              1 non-null      object
 18  curation.author            1 non-null      object
 19  curation.structure_source  1 non-null      object
 20  curation.num_species       1 non-null      int64
dtypes: float64(3), int64(3), object(15)
memory usage: 300.0+ bytes

--- Conteo de valores nulos por columna ---
id                           0
comment                      0
acc                          0
description                  0
cm.build_command             0
cm.calibrate_command         0
cm.search_command            0
cm.cutoffs.noise             0
cm.cutoffs.trusted           0
cm.cutoffs.gathering         0
clan.acc                     1
clan.id                      1
release.number               0
release.date                 0
curation.num_full            0
curation.num_seed            0
curation.seed_source         0
curation.type                0
curation.author              0
curation.structure_source    0
curation.num_species         0
dtype: int64

# Task
Perfecto. Para continuar con el análisis comparativo, necesito que me proporciones los identificadores (IDs) de las familias Rfam adicionales con las que deseas comparar `RF00360`.

Por favor, ingresa los IDs separados por comas (por ejemplo: RF00003`RF00001, RF00002, `).

## Solicitar IDs de Familias Rfam Adicionales

### Subtask:
Pedir al usuario que ingrese los IDs de las familias Rfam adicionales para la comparación.

Para comparar con otras familias Rfam, por favor, introduce los IDs de las familias adicionales separados por comas (por ejemplo: `RF00001, RF00002, RF00003`).

**Reasoning**:
Next, I will use a code block to prompt the user for the additional Rfam IDs and store the input in the `additional_rfam_ids_input` variable, as per the subtask instructions.

In [6]:
additional_rfam_ids_input = input("Por favor, introduce los IDs de las familias Rfam adicionales (separados por comas): ")
print(f"Has introducido: {additional_rfam_ids_input}")

Por favor, introduce los IDs de las familias Rfam adicionales (separados por comas): RF00001, RF00005, RF00023, RF00174
Has introducido: RF00001, RF00005, RF00023, RF00174

## Descargar y Guardar Datos Adicionales de Rfam

### Subtask:
Una vez que tenga los IDs de las familias, realizaré peticiones GET a la API de Rfam para cada ID, similar a cómo se hizo con RF00360. Guardaré cada respuesta JSON en un archivo local separado (ej. 'rfam_ID.json').

**Reasoning**:
The subtask requires cleaning the input string of Rfam IDs, iterating through them, making API calls, and saving the responses to individual JSON files. This code block will perform all these actions, including importing necessary libraries, handling potential errors, and tracking downloaded files.

In [7]:
import json
import requests
import os

# Clean and split the additional_rfam_ids_input string
# Remove any leading/trailing whitespace and split by commas
rfam_ids = [id.strip() for id in additional_rfam_ids_input.split(',') if id.strip()]

# Create an empty list to keep track of the files saved
downloaded_files = []

print(f"Starting download for {len(rfam_ids)} additional Rfam families...")

# Loop through each Rfam ID in the cleaned list
for rfam_id in rfam_ids:
    base_url = 'https://rfam.org/family/'
    api_url = f"{base_url}{rfam_id}?content-type=application/json"
    file_name = f"rfam_{rfam_id}.json"

    try:
        # Make a GET request to the constructed URL
        r = requests.get(api_url)

        # Check if the request was successful (status code 200)
        r.raise_for_status() # Raises an HTTPError for bad responses (4xx or 5xx)

        # Parse the JSON response
        data = r.json()

        # Save the JSON data to a local file
        with open(file_name, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)

        downloaded_files.append(file_name)
        print(f"Successfully downloaded and saved '{file_name}'")

    except requests.exceptions.RequestException as e:
        print(f"Error downloading data for {rfam_id}: {e}")
    except json.JSONDecodeError:
        print(f"Error decoding JSON for {rfam_id}. Response content: {r.text[:200]}...")
    except Exception as e:
        print(f"An unexpected error occurred for {rfam_id}: {e}")

print("\n--- Download Summary ---")
if downloaded_files:
    print(f"Downloaded {len(downloaded_files)} files:")
    for f in downloaded_files:
        print(f"- {f}")
else:
    print("No additional Rfam family data was downloaded.")

print("Download and saving process complete.")

Starting download for 4 additional Rfam families...
Successfully downloaded and saved 'rfam_RF00001.json'
Successfully downloaded and saved 'rfam_RF00005.json'
Successfully downloaded and saved 'rfam_RF00023.json'
Successfully downloaded and saved 'rfam_RF00174.json'

--- Download Summary ---
Downloaded 4 files:
- rfam_RF00001.json
- rfam_RF00005.json
- rfam_RF00023.json
- rfam_RF00174.json
Download and saving process complete.

## Cargar y Combinar Datos de Rfam en un Único DataFrame

### Subtask:
Cargar todos los archivos JSON (incluyendo el original `rfam_RF00360.json` y los recién descargados) en DataFrames individuales y luego combinarlos en un único DataFrame para facilitar la comparación.

#### Instructions
1. Crear una lista que contenga los nombres de todos los archivos JSON a cargar, incluyendo `rfam_RF00360.json` y los archivos listados en `downloaded_files`.
2. Iterar sobre esta lista de archivos.
3. Para cada archivo, cargarlo como un DataFrame de pandas usando `pd.json_normalize` y accediendo a la clave 'rfam'.
4. Almacenar cada DataFrame en una lista.
5. Concatenar todos los DataFrames de la lista en un único DataFrame final.
6. Mostrar las primeras filas y la información general (`.info()`) del DataFrame combinado para verificar su estructura y tipos de datos.

**Reasoning**:
This code block will implement the instructions outlined in the previous markdown block: loading all specified JSON files, normalizing their 'rfam' content into individual DataFrames, and then concatenating them into one comprehensive DataFrame for analysis. It will also print the head and info of the final DataFrame for verification.

In [8]:
import pandas as pd
import json

# List of all JSON files to load
# The original rfam_RF00360.json is already present
# downloaded_files contains the new ones
all_rfam_json_files = ['rfam_RF00360.json'] + downloaded_files

# List to store individual DataFrames
df_list = []

print(f"Loading and processing {len(all_rfam_json_files)} Rfam JSON files...")

# Iterate through each file, load it, normalize, and add to the list
for file_name in all_rfam_json_files:
    try:
        with open(file_name, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Normalize the 'rfam' key from the JSON data
        # We need to ensure that the structure is consistent. If 'rfam' key might not exist in some valid responses,
        # it's better to check or handle potential KeyError. However, based on previous steps, it should be present.
        df_temp = pd.json_normalize(data['rfam'])
        df_list.append(df_temp)
        print(f"Successfully loaded '{file_name}' and added to DataFrame list.")
    except FileNotFoundError:
        print(f"Error: File '{file_name}' not found. Skipping.")
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from '{file_name}'. Skipping.")
    except KeyError as e:
        print(f"Error: Missing key '{e}' in JSON from '{file_name}'. Skipping.")
    except Exception as e:
        print(f"An unexpected error occurred while processing '{file_name}': {e}. Skipping.")

# Concatenate all DataFrames in the list into a single DataFrame
if df_list:
    combined_df = pd.concat(df_list, ignore_index=True)
    print("\nAll DataFrames combined successfully.")
    print("\n--- Combined DataFrame Head ---")
    display(combined_df.head())

    print("\n--- Combined DataFrame Info ---")
    combined_df.info()
else:
    print("No DataFrames were loaded to combine.")

Loading and processing 5 Rfam JSON files...
Successfully loaded 'rfam_RF00360.json' and added to DataFrame list.
Successfully loaded 'rfam_RF00001.json' and added to DataFrame list.
Successfully loaded 'rfam_RF00005.json' and added to DataFrame list.
Successfully loaded 'rfam_RF00023.json' and added to DataFrame list.
Successfully loaded 'rfam_RF00174.json' and added to DataFrame list.

All DataFrames combined successfully.

--- Combined DataFrame Head ---

,id,comment,acc,description,cm.build_command,cm.calibrate_command,cm.search_command,cm.cutoffs.noise,cm.cutoffs.trusted,cm.cutoffs.gathering,...,clan.id,release.number,release.date,curation.num_full,curation.num_seed,curation.seed_source,curation.type,curation.author,curation.structure_source,curation.num_species
0,snoZ107_R87,Z107 and R87 are members of the C/D class of s...,RF00360,Small nucleolar RNA Z107/R87,cmbuild -F CM SEED,cmcalibrate --mpi CM,cmsearch --cpu 4 --verbose --nohmmonly -T 19.0...,49.7,50.0,50.0,...,None,15.1,2026-01-16,783,9,Moxon SJ,Gene; snRNA; snoRNA; CD-box;,Moxon SJ,"Predicted; RNAfold; Moxon SJ, Daub J, Gardner PP",221
1,5S_rRNA,5S ribosomal RNA (5S rRNA) is a component of t...,RF00001,5S ribosomal RNA,cmbuild -F CM SEED,cmcalibrate --mpi CM,cmsearch --cpu 4 --verbose --nohmmonly -T 24.9...,37.9,38.0,38.0,...,None,15.1,2026-01-16,594154,712,"Szymanski et al, 5S ribosomal database, PMID:1...",Gene; rRNA;,"Griffiths-Jones SR, Mifsud W, Gardner PP",Published; PMID:11283358,12253
2,tRNA,Transfer RNA (tRNA) molecules are approximatel...,RF00005,tRNA,cmbuild -F CM SEED,cmcalibrate --mpi CM,cmsearch --cpu 4 --verbose --nohmmonly -T 22.0...,28.9,29.0,29.0,...,None,15.1,2026-01-16,5335975,954,Eddy SR,Gene; tRNA;,"Eddy SR, Griffiths-Jones SR, Mifsud W",Published; PMID:8256282,14413
3,tmRNA,"Bacterial tmRNA, also known as 10Sa RNA or Ssr...",RF00023,transfer-messenger RNA,cmbuild -F CM SEED,cmcalibrate --mpi CM,cmsearch --cpu 4 --verbose --nohmmonly -T 16.6...,46.9,47.1,47.0,...,None,15.1,2026-01-16,8092,477,Published; PMID:19617710,Gene;,Gardner PP,Published; PMID:19617710,8241
4,Cobalamin,Riboswitches are metabolite binding domains wi...,RF00174,Cobalamin riboswitch aptamer,cmbuild -F CM SEED,cmcalibrate --mpi CM,cmsearch --cpu 4 --verbose --nohmmonly -T 30.0...,31.4,31.5,31.5,...,None,15.1,2026-01-16,20864,434,"Barrick JE, Breaker RR",Cis-reg; riboswitch;,"Barrick JE, Breaker RR, Moxon SJ, Gardner PP, ...",Predicted; PFOLD,7605

--- Combined DataFrame Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         5 non-null      object
 1   comment                    5 non-null      object
 2   acc                        5 non-null      object
 3   description                5 non-null      object
 4   cm.build_command           5 non-null      object
 5   cm.calibrate_command       5 non-null      object
 6   cm.search_command          5 non-null      object
 7   cm.cutoffs.noise           5 non-null      float64
 8   cm.cutoffs.trusted         5 non-null      float64
 9   cm.cutoffs.gathering       5 non-null      float64
 10  clan.acc                   0 non-null      object
 11  clan.id                    0 non-null      object
 12  release.number             5 non-null      object
 13  release.date               5 non-null      object
 14  curation.num_full          5 non-null      int64
 15  curation.num_seed          5 non-null      int64
 16  curation.seed_source       5 non-null      object
 17  curation.type              5 non-null      object
 18  curation.author            5 non-null      object
 19  curation.structure_source  5 non-null      object
 20  curation.num_species       5 non-null      int64
dtypes: float64(3), int64(3), object(15)
memory usage: 972.0+ bytes

## Realizar Análisis Comparativo Inicial

### Subtask:
Realizar una comparación inicial de los datos consolidados en `combined_df`, mostrando información general, estadísticas de columnas numéricas y preguntando al usuario sobre análisis adicionales.

## Resumen:

### Preguntas y respuestas
Se le pidió al usuario que proporcionara identificadores Rfam adicionales para comparar con `RF00360`. Los identificadores proporcionados fueron `RF00001, RF00005, RF00023, RF00174`.

### Hallazgos Clave del Análisis de Datos
* El usuario proporcionó con éxito cuatro IDs adicionales de Rfam (`RF00001`, `RF00005`, `RF00023`, `RF00174`) para análisis comparativo con `RF00360`.
* Los datos para estas cuatro familias adicionales de Rfam se descargaron con éxito desde la API de Rfam y se guardaron como archivos JSON individuales (por ejemplo, `rfam_RF00001.json`).
* Los cinco archivos JSON de Rfam (incluido el inicial `rfam_RF00360.json` y los cuatro recién descargados) se cargaron, analizaron y combinaron con éxito en un único DataFrame de Pandas llamado `combined_df`.
* El `combined_df` contiene 5 entradas, correspondientes a las 5 familias de Rfam, y 21 columnas, lo que indica un conjunto de datos exhaustivo para comparación. La cabecera del DataFrame confirma la presencia de datos para todas las familias especificadas, incluyendo `RF00360` (snoZ107_R87), `RF00001` (5S_rRNA), `RF00005` (tRNA), `RF00023` (tmRNA) y `RF00174` (Cobalamin).

### Ideas o Próximos Pasos
* El `combined_df` ahora está estructurado adecuadamente para realizar un análisis comparativo directo entre las familias Rfam seleccionadas, lo que permite obtener ideas sobre características compartidas o distintivas.
* El siguiente paso lógico es realizar el análisis comparativo real usando el `combined_df`, lo que puede implicar estadísticas descriptivas, visualización de datos o comparaciones específicas de métricas y características clave entre las familias Rfam incluidas.